import FaqInterface from "../interfaces/FaqInterface";
import { MerchantInterface, UserInterface } from "../interfaces/UserInterface";
import Store from "../interfaces/StoreInterface";
import Verification from "../interfaces/Verification";

export const faqs: FaqInterface[] = [
  {
    id: 1,
    question: "How do I reset my password?",
    answer:
      "To reset your password, go to the login page and click on 'Forgot Password'. Follow the instructions to reset it via email.",
  },
  {
    id: 2,
    question: "Where can I find my purchase history?",
    answer:
      "You can find your purchase history under the 'Orders' section in your account dashboard.",
  },
  {
    id: 3,
    question: "How do I update my profile information?",
    answer:
      "To update your profile information, go to the 'Profile' section in your dashboard and click on 'Edit Profile'. Make the necessary changes and save.",
  },
  {
    id: 4,
    question: "What should I do if I encounter an error?",
    answer:
      "If you encounter an error, please contact our support team with the details of the issue. You can also refer to our troubleshooting guide in the Help section.",
  },
  {
    id: 5,
    question: "Can I change my subscription plan?",
    answer:
      "Yes, you can change your subscription plan at any time. Go to the 'Subscription' section and select the plan you want to switch to. Follow the prompts to confirm the change.",
  },
  {
    id: 6,
    question: "How do I contact customer support?",
    answer:
      "You can contact customer support via the 'Support' section in your dashboard. We offer support through chat, email, and phone.",
  },
  {
    id: 7,
    question: "What payment methods are accepted?",
    answer:
      "We accept various payment methods including credit/debit cards, PayPal, and bank transfers. Check the 'Payments' section for more details.",
  },
  {
    id: 8,
    question: "How do I deactivate my account?",
    answer:
      "To deactivate your account, go to the 'Settings' section and click on 'Account'. Select 'Deactivate Account' and follow the steps to confirm your decision.",
  },
  {
    id: 9,
    question: "Is my data secure?",
    answer:
      "Yes, we prioritize your data security by implementing industry-standard encryption and data protection practices. Read our Privacy Policy for more information.",
  },
  {
    id: 10,
    question: "How do I track my order?",
    answer:
      "To track your order, go to the 'Orders' section and click on the specific order you want to track. You'll find the tracking details and the current status of your order.",
  },
];

export const merchants: MerchantInterface[] = [
  {
    id: 1,
    first_name: "Alice",
    last_name: "Smith",
    email: "alice.smith@example.com",
    phone_number: "+1234567890",
    image: "https://picsum.photos/200/300?random=1",
    role: "merchant",
    blocked: false,
    merchant_id: 201,
    verified: true,
  },
  {
    id: 2,
    first_name: "Bob",
    last_name: "Johnson",
    email: "bob.johnson@example.com",
    phone_number: "+1234567891",
    image: "https://picsum.photos/200/300?random=2",
    role: "merchant",
    blocked: false,
    merchant_id: 202,
    verified: false,
  },
  {
    id: 3,
    first_name: "Charlie",
    last_name: "Brown",
    email: "charlie.brown@example.com",
    phone_number: "+1234567892",
    image: "https://picsum.photos/200/300?random=3",
    role: "merchant",
    blocked: true,
    merchant_id: 203,
    verified: true,
  },
  {
    id: 4,
    first_name: "Diana",
    last_name: "Prince",
    email: "diana.prince@example.com",
    phone_number: "+1234567893",
    image: "https://picsum.photos/200/300?random=4",
    role: "merchant",
    blocked: false,
    merchant_id: 204,
    verified: true,
  },
  {
    id: 5,
    first_name: "Eve",
    last_name: "Evans",
    email: "eve.evans@example.com",
    phone_number: "+1234567894",
    image: "https://picsum.photos/200/300?random=5",
    role: "merchant",
    blocked: false,
    merchant_id: 205,
    verified: false,
  },
  {
    id: 6,
    first_name: "Frank",
    last_name: "Wright",
    email: "frank.wright@example.com",
    phone_number: "+1234567895",
    image: "https://picsum.photos/200/300?random=6",
    role: "merchant",
    blocked: true,
    merchant_id: 206,
    verified: false,
  },
  {
    id: 7,
    first_name: "Grace",
    last_name: "Hopper",
    email: "grace.hopper@example.com",
    phone_number: "+1234567896",
    image: "https://picsum.photos/200/300?random=7",
    role: "merchant",
    blocked: false,
    merchant_id: 207,
    verified: true,
  },
  {
    id: 8,
    first_name: "Hank",
    last_name: "Hill",
    email: "hank.hill@example.com",
    phone_number: "+1234567897",
    image: "https://picsum.photos/200/300?random=8",
    role: "merchant",
    blocked: true,
    merchant_id: 208,
    verified: false,
  },
  {
    id: 9,
    first_name: "Ivy",
    last_name: "Lee",
    email: "ivy.lee@example.com",
    phone_number: "+1234567898",
    image: "https://picsum.photos/200/300?random=9",
    role: "merchant",
    blocked: false,
    merchant_id: 209,
    verified: true,
  },
  {
    id: 10,
    first_name: "Jack",
    last_name: "Black",
    email: "jack.black@example.com",
    phone_number: "+1234567899",
    image: "https://picsum.photos/200/300?random=10",
    role: "merchant",
    blocked: false,
    merchant_id: 210,
    verified: false,
  },
];

export const stores: Store[] = [
  {
    id: 101,
    name: "Tech Gadgets",
    type: "verified_vendor",
    merchant_id: 1001,
  },
  {
    id: 102,
    name: "Fashionista",
    type: "free_vendor",
    merchant_id: 1002,
  },
  {
    id: 103,
    name: "Books & Beyond",
    type: "verified_vendor",
    merchant_id: 1003,
  },
  {
    id: 104,
    name: "Gourmet Groceries",
    type: "free_vendor",
  },
  {
    id: 105,
    name: "Electro World",
    type: "verified_vendor",
    merchant_id: 1005,
  },
  {
    id: 106,
    name: "Home Essentials",
    type: "free_vendor",
  },
  {
    id: 107,
    name: "Outdoor Adventure",
    type: "verified_vendor",
    merchant_id: 1007,
  },
  {
    id: 108,
    name: "Pet Paradise",
    type: "free_vendor",
  },
  {
    id: 109,
    name: "Toy Universe",
    type: "verified_vendor",
    merchant_id: 1009,
  },
  {
    id: 110,
    name: "Beauty Bliss",
    type: "free_vendor",
    merchant_id: 1010,
  },
];

export const customers: UserInterface[] = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    phone_number: "+1234567890",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
  {
    id: 2,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@example.com",
    phone_number: "+1987654321",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
  {
    id: 3,
    first_name: "Michael",
    last_name: "Johnson",
    email: "michael.johnson@example.com",
    phone_number: "+1122334455",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: true,
  },
  {
    id: 4,
    first_name: "Emily",
    last_name: "Brown",
    email: "emily.brown@example.com",
    phone_number: "+1654321876",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
  {
    id: 5,
    first_name: "William",
    last_name: "Miller",
    email: "william.miller@example.com",
    phone_number: "+1987263541",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
  {
    id: 6,
    first_name: "Sophia",
    last_name: "Davis",
    email: "sophia.davis@example.com",
    phone_number: "+1765432987",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
  {
    id: 7,
    first_name: "James",
    last_name: "Wilson",
    email: "james.wilson@example.com",
    phone_number: "+1345678901",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
  {
    id: 8,
    first_name: "Olivia",
    last_name: "Martinez",
    email: "olivia.martinez@example.com",
    phone_number: "+1876543210",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
  {
    id: 9,
    first_name: "Alexander",
    last_name: "Garcia",
    email: "alexander.garcia@example.com",
    phone_number: "+1567890123",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: true,
  },
  {
    id: 10,
    first_name: "Ava",
    last_name: "Lopez",
    email: "ava.lopez@example.com",
    phone_number: "+1980123456",
    image: "https://picsum.photos/200/300",
    role: "customer",
    blocked: false,
  },
];

export const verifications: Verification[] = [
  {
    id: 1,
    commercial_record: "https://picsum.photos/200/300?random=1",
    merchant_id: 101,
    store_id: 201,
    store_name: "Tech Haven",
    merchant_name: "John Doe",
    status: "pending",
  },
  {
    id: 2,
    commercial_record: "https://picsum.photos/200/300?random=2",
    merchant_id: 102,
    store_id: 202,
    store_name: "Book World",
    merchant_name: "Jane Smith",
    status: "accepted",
  },
  {
    id: 3,
    commercial_record: "https://picsum.photos/200/300?random=3",
    merchant_id: 103,
    store_id: 203,
    store_name: "Gadget Pro",
    merchant_name: "Michael Johnson",
    status: "rejected",
  },
  {
    id: 4,
    commercial_record: "https://picsum.photos/200/300?random=4",
    merchant_id: 104,
    store_id: 204,
    store_name: "Fashion Hub",
    merchant_name: "Emily Brown",
    status: "pending",
  },
  {
    id: 5,
    commercial_record: "https://picsum.photos/200/300?random=5",
    merchant_id: 105,
    store_id: 205,
    store_name: "Foodies Delight",
    merchant_name: "William Miller",
    status: "accepted",
  },
  {
    id: 6,
    commercial_record: "https://picsum.photos/200/300?random=6",
    merchant_id: 106,
    store_id: 206,
    store_name: "Fitness First",
    merchant_name: "Sophia Davis",
    status: "rejected",
  },
  {
    id: 7,
    commercial_record: "https://picsum.photos/200/300?random=7",
    merchant_id: 107,
    store_id: 207,
    store_name: "Home Essentials",
    merchant_name: "James Wilson",
    status: "pending",
  },
  {
    id: 8,
    commercial_record: "https://picsum.photos/200/300?random=8",
    merchant_id: 108,
    store_id: 208,
    store_name: "Beauty Bliss",
    merchant_name: "Olivia Martinez",
    status: "accepted",
  },
  {
    id: 9,
    commercial_record: "https://picsum.photos/200/300?random=9",
    merchant_id: 109,
    store_id: 209,
    store_name: "Toy Town",
    merchant_name: "Alexander Garcia",
    status: "rejected",
  },
  {
    id: 10,
    commercial_record: "https://picsum.photos/200/300?random=10",
    merchant_id: 110,
    store_id: 210,
    store_name: "Pet Paradise",
    merchant_name: "Ava Lopez",
    status: "pending",
  },
];
